version: '2'
services:
  jenkinsjhip-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/jenkinsjhip/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jenkinsjhip
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
